name: quent-tech-infra
description: Infrastructure for quent-tech.com
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
